### ISSUE TITLE
Test and deploy method

### ISSUE THREAD

**Issue by jemacom** [kamronk/AtHomeWallet#1]
Hi kamronk , 
Can you please share your dev enviroment  : 
version of eclipse ? 
version of Tomcat ? 

And how can I test the project ? 

Thanks in advance.

**Comment by kamronk** [comment]
Hello!

Java 1.7 and I was using Tomcat 7, and Eclipse Mars would be fine. Make sure you are getting the Eclipse for Java EE developers so that it comes with all of the web tools/views.

Let me know if you need more info! Happy to provide

**Comment by kamronk** [comment]
To test, check out the source, import the project root directory as an Existing project in eclipse. Then go to the Servers pane in the Java EE view in eclipse, create a server and make sure this project is Added to it. Then start the server, and visit the following URL in your web browser: http://localhost:8080/AtHomeWallet/

**Comment by kamronk** [comment]
Please let me know if you run into any issues in testing.
